const rows=(window.DB&&window.DB.roscas)||[];
const params=new URLSearchParams(location.search); const wanted=params.get('passo'); const wantedType=params.get('tipo');
function norm(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[×x]/g,'x').replace(/\s+/g,'').replace(/\./g,',');}
function label(r){return r.tipo.startsWith('M ') ? `M${r.passo.replace('x',' × ')}` : r.passo.replace('x',' × ');}
const row=rows.find(r=>norm(r.passo)===norm(wanted||'') && (!wantedType||r.tipo===wantedType)) || rows.find(r=>norm(label(r))===norm(wanted||''));
if(!row){document.querySelector('#detailContent').innerHTML='<section class="detail-error"><b>Não encontrei esta rosca.</b><p>Volte para a lista e escolha uma medida cadastrada.</p><a href="roscas.html">Voltar para Roscas</a></section>';}
else{
 const title=label(row); document.title=`${title} — Usinagem Fácil`; document.querySelector('#detailTitle').textContent=title; document.querySelector('#detailType').textContent=row.tipo; const hasDrill=!!row.broca; document.querySelector('#drillValue').textContent=hasDrill?row.broca:'Pendente'; document.querySelector('#processDrill').textContent=hasDrill?`Ø ${row.broca} mm`:'Validar na WestTools'; document.querySelector('#processThread').textContent=title;
 let diameter='Consulte a medida'; let pitch='Consulte a medida'; const m=title.match(/^M\s*(\d+(?:[.,]\d+)?)\s*×\s*(\d+(?:[.,]\d+)?)/i); if(m){diameter=`Ø ${m[1]} mm`;pitch=`${m[2]} mm`;document.querySelector('#diameterTag').textContent=`Ø ${m[1]} mm`;document.querySelector('#pitchTag').textContent=`Passo ${m[2]} mm`;document.querySelector('#learnText').textContent=`${title}: “M${m[1]}” indica o diâmetro nominal e “${m[2]}” indica o passo.`;document.querySelector('#technicalText').textContent=hasDrill?`${title} é uma rosca métrica cadastrada como “${row.tipo}”. Na tabela do aplicativo, a broca indicada para o furo é Ø ${row.broca} mm.`:`${title} está cadastrada, mas a broca permanece pendente de validação manual WestTools.`;}else{document.querySelector('#diameterHelp').textContent='Identificação conforme a nomenclatura desta família de rosca.';document.querySelector('#pitchHelp').textContent='A forma de indicar o passo depende da família da rosca.';document.querySelector('#learnText').textContent=`${title} pertence à família ${row.tipo}.`;document.querySelector('#technicalText').textContent=hasDrill?`Para ${title}, a tabela técnica cadastrada no aplicativo indica broca Ø ${row.broca} mm.`:`${title} já possui estrutura técnica cadastrada, mas o diâmetro de pré-furo será preenchido somente após a validação manual com a tabela WestTools.`;}
 document.querySelector('#diameterValue').textContent=diameter;document.querySelector('#pitchValue').textContent=pitch;
 document.querySelector('#learnButton').onclick=()=>{const d=document.querySelector('.technical-box');d.open=true;d.scrollIntoView({behavior:'smooth',block:'center'});};
}
